shop419/cart/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('cart/', views.viewCart, name = 'view_cart'),
    path('cart/add/<int:product_id>', views.addToCart, name = 'add_to_cart' ),
    path('cart/remove/<int:cart_item_id>', views.remFromCart, name = 'remove_from_cart'),
    path('cart/add/<int:cart_item_id>/', views.addQuantity, name='add_quantity'),
    path('cart/remove/<int:cart_item_id>/', views.remQuantity, name='rem_quantity'),
]

shop419/mainapp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.homeView, name = "home"),
    path("about", views.aboutView, name = "aboutpage"),
    path("products/add", views.AddProduct.as_view(), name = "addproduct"),
    path("Products/int<pk>", views.ProductDetails.as_view(), name = "prod_details"),
    path("Products/edit/<int:pk>", views.UpdateProduct.as_view(), name = "editproduct"),
    path("Products/del/<int:pk>", views.DeleteProduct.as_view(), name = "delproduct"),

    path('products/search', views.SearchView, name = "search"),
]

shop419/shop419/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('cart/',include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payments/',include('payments.urls')),
    path('auth/',include('authentication.urls')),
    path('auth/',include('django.contrib.auth.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop419/mainapp/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField(null = False)
    desc = models.TextField()
    pic = models.ImageField(upload_to = "products/", null = False)
    stock = models.PositiveIntegerField(default = 1)
    

shop419/mainapp/views.py
from django.shortcuts import render
from .models import Product
from django.http import HttpResponse
from django.template import loader
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.urls import reverse_lazy, reverse
# Create your views here.
def homeView(request):
    products = Product.objects.all()
    context ={
        'product_list': products
    }
    template = loader.get_template('home.html')
    return HttpResponse(template.render(context, request))

def aboutView(request):
    context = {
        'name': "Ayan",
        'students': [
            "Varun",
            "Harsha",
            "Srikanth",
        ],
        'slept':  False,

    }
    template = loader.get_template('about.html')
    return HttpResponse(template.render(context, request))

class AddProduct(CreateView):
    model = Product
    fields = ['name', 'price', 'desc', 'pic', 'stock']
    template_name = 'addproduct.html'
    success_url = reverse_lazy('home')

#read
class ProductDetails(DetailView):
    model = Product
    template_name = 'prod_details.html'
    context_object_name = 'prod'

#update
class UpdateProduct(UpdateView):
    model = Product
    fields = '__all__'
    template_name = 'editproduct.html'
    def get_success_url(self):
        return reverse_lazy('prod_details', kwargs={'pk': self.object.pk})


#delete
class DeleteProduct(DeleteView):
    model = Product
    template_name = 'delproduct.html'
    success_url = reverse_lazy('home')


def SearchView(request):
    query = request.GET.get('search_text') 
    
    results = Product.objects.filter(name__icontains = query) 
    
    context = {
        'items' : results,
        'query' : query
    }
    template = loader.get_template('searchResults.html')
    return HttpResponse(template.render(context, request))

shop419/mainapp/templates/about.html
{% extends 'base.html' %}


{% block title %}
About 
{% endblock %}

{% block content %}
    <ul>
        {% for student in students %}
            <li>{{student}}</li>
        {% endfor %}
    </ul>

    <!-- Conditionals -->
     {% if slept %}
     I slept
     {% else %}
     Did not sleep
     {% endif %}
    
{% endblock %}

shop419/mainapp/templates/addproduct.html
{% extends 'base.html' %}

{% block title %}
Add Product
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name : </label>
        {{form.name}}
    </div>
    <div class="form-group">
        <label for="id_price">Price : </label>
        {{form.price}}
    </div>
    <div class="form-group">
        <label for="id_desc">Description : </label>
        {{form.desc}}
    </div>
    <div class="form-group">
        <label for="id_stock">Stock : </label>
        {{form.stock}}
    </div>
    <div class="form-group">
        <label for="id_pic">Pic : </label>
        {{form.pic}}
    </div>
    <button type="submit">Add Product</button>

</form>
{% endblock %}

shop419/mainapp/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'icon/logo_wobg.ico' %}" type="image/x-icon">
</head>

<body>
    <header class="position-fixed top-0 start-0 end-0">
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">

                <a class="navbar-brand" href="{% url 'home'%}">
                    <img src="{% static 'image\logo_wobg.png' %}" alt="Logo" width="40" height="40"
                        class="d-inline-block align-text-top">
                    Bshoping site
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link {% if current_page == 'home' %}border disabled{% else %}active{% endif %}" aria-current="page" href="{% url 'home'%}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if current_page == 'about' %}border disabled{% else %}active{% endif %}" href="{% url 'aboutpage'%}">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'order_history' %}">Past Orders</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        {% if user.is_authenticated %}
                            {% if user.is_staff %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'addproduct'%}">Add Product</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'view_cart' %}">My cart</a>
                            </li>
                        {% endif %}
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" method="get" action="{% url 'search' %}">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_text">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button class="nav-link">Logout</button>
                            </form>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-info" aria-current="page" href="{% url 'signin' %}">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" aria-current="page" href="{% url 'signup' %}">Sign Up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="position-fixed bottom-0 start-0 end-0 text-center bg-secondary-subtle">
        &copy; 2025 shoping site
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>


</html>

shop419/mainapp/templates/delproduct.html
{% extends 'base.html' %}
{% block title %}
Delete Product
{% endblock %}

{% block content %}
<div class="text-center">
    <p>
        The product : {{product.name}} will be deleted...
    </p>
</div>
<form method="post" enctype="multipart/form-data" class="form text-center">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Confirm delete</button>
    <a href="{% url 'prod_details' product.pk %}">Cancel</a>

</form>
{% endblock %}

shop419/mainapp/templates/editproduct.html
{% extends 'base.html' %}

{% block title %}
Edit > {{ product.name}}
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="form">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit">Save changes</button>

</form>
{% endblock %}

shop419/mainapp/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}
{% block content %}
<div class="home">
<div class="container">
    {% for product in product_list %}
    <div class="card">
        <div class="card_img">
            <img src="{{product.pic}}" alt="image not found">
        </div>
        <div class="card_text">
            <h4>
                <a href="{% url 'prod_details' product.id %}">
                    {{product.name}}
                </a>
            </h4>
            <h6>Price : <ins>{{product.price}}</ins></h6>
            <h6>Stock : <ins>{{product.stock}}</ins></h6>
            <p> Description :
                <br><ins>{{product.desc}}</ins>
            </p>
            {% if user.is_staff %}
            <a href="{% url 'prod_details' product.id %}">
                <button type="button">Edit the product</button>
            </a>
            {% else %}
            <a href="{% url 'add_to_cart' product.id %}">
                <button type="button">Add to cart</button>
            </a>
            {% endif %}
        </div>
    </div>
    {% endfor %}

</div>
</div>
{% endblock %}

shop419/mainapp/templates/prod_details.html
{% extends 'base.html' %}


{% block title %}
{{ prod.name }}
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-sm-6 ">
        <img src="{{prod.pic.url}}" class="w-100 h-100" alt="">
    </div>
    <div class="col-sm-6">
        <div class="row">
            <h1>{{ prod.name }}</h1>
            <p>Rs.{{ prod.price }}</p>
        </div>
        <div class="row">
            {% if user.is_staff %}
            <a href="{% url 'editproduct' prod.pk %}" class="btn btn-secondary">Edit Product</a>
            <a href="{% url 'delproduct' prod.pk %}" class="btn btn-danger">Delete Product</a>
            {% else %}
            <a href="#" class="btn btn-secondary">Add to Cart</a>
            {% endif %}
        </div>

    </div>

</div>
{% endblock %}

shop419/mainapp/templates/searchResults.html
{% extends 'base.html' %}

{% block title %}
Search Results
{% endblock %}

{% block content %}
<h2>Searching results for {{query}}</h2>
<div class="container">
    {% for product in items %}
    <div class="card">
        <div class="card_img">
            <img src="{{product.pic.url}}" alt="image not found">
        </div>
        <div class="card_text">
            <h4>
                <a href="{% url 'prod_details' product.id %}" >
                    {{product.name}}
                </a>
            </h4>
            <h6>Price : <ins>{{product.price}}</ins></h6>
            <h6>Stock : <ins>{{product.stock}}</ins></h6>
            <p> Description :
                <br><ins>{{product.desc}}</ins>
            </p>
            <button type="button">Add to cart</button>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}